### PR TITLE
Added Test2 class to BranchX

### PR DESCRIPTION
**Pull request by jagdish-github**
Hi,

I have commited Test2. Please review it.

Regards,
X

### CODE REVIEW

**Comment by jagdish-github** [comment]
Hi X,

Your code looks good. Please add one more check.

Regards,
P

**Comment by jagdishpt20** [comment]
Hi X,

Your code looks good. Please add one more check.

Regards,
P

**Comment by jagdish-github** [comment]
Hi P,

I have added additional checks. Please review it.

Regards,
X

**Comment by jagdishpt20** [comment]
Hi X,

All looks well. Go ahead and merge to master branch.

Regards,
P

**Pull request merged**
